# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43605094acb9447e4ed94ec9913bb48bc5f13579fc8e68c5158a825b546e14608d057245a8bee43b5a75e5b2c9ad52492e6620bc65588b94139b19de78b89e4b

test:
  secret_key_base: b0e24a49924c02d164dee342470855574c2674db31b49728a00def52598999f426ca4c07e2b09da1ddb9235fb1b9cf498ccf452a75e4cbef8b5129801589091c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
